"""initial_migration

Revision ID: ec8f8c32bc5c
Revises:
Create Date: 2025-12-02 23:51:18.297706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8f8c32bc5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('telegramuser_telegram_id'), 'telegramuser', ['telegram_id'], unique=1)
    op.alter_column('telegramuser', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('team_name_league_id'), 'team', ['name', 'league_id'], unique=1)
    op.create_index(op.f('team_league_id'), 'team', ['league_id'], unique=False)
    op.alter_column('team', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'notificationlog', type_='foreignkey')
    op.create_foreign_key(None, 'notificationlog', 'bettingopportunity', ['opportunity_id'], ['id'])
    op.create_index(op.f('notificationlog_user_id'), 'notificationlog', ['user_id'], unique=False)
    op.create_index(op.f('notificationlog_opportunity_id'), 'notificationlog', ['opportunity_id'], unique=False)
    op.alter_column('notificationlog', 'success',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('notificationlog', 'sent_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('notificationlog', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('match_unique_teams_season'), 'match', ['league_id', 'home_team_id', 'away_team_id', 'season'], unique=1)
    op.create_index(op.f('match_league_id_home_team_id_away_team_id_season'), 'match', ['league_id', 'home_team_id', 'away_team_id', 'season'], unique=1)
    op.create_index(op.f('match_league_id'), 'match', ['league_id'], unique=False)
    op.create_index(op.f('match_home_team_id'), 'match', ['home_team_id'], unique=False)
    op.create_index(op.f('match_away_team_id'), 'match', ['away_team_id'], unique=False)
    op.alter_column('match', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('match', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('match', 'red_cards_away',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'red_cards_home',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('league_name_country'), 'league', ['name', 'country'], unique=1)
    op.alter_column('league', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('league', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_table('admin_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=1)
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=1)
    # ### end Alembic commands ###


def downgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_table('admin_user')
    op.alter_column('league', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('league', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('league_name_country'), table_name='league')
    op.alter_column('match', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('match', 'red_cards_home',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'red_cards_away',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('match', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('match_away_team_id'), table_name='match')
    op.drop_index(op.f('match_home_team_id'), table_name='match')
    op.drop_index(op.f('match_league_id'), table_name='match')
    op.drop_index(op.f('match_league_id_home_team_id_away_team_id_season'), table_name='match')
    op.drop_index(op.f('match_unique_teams_season'), table_name='match')
    op.alter_column('notificationlog', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notificationlog', 'sent_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('notificationlog', 'success',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.drop_index(op.f('notificationlog_opportunity_id'), table_name='notificationlog')
    op.drop_index(op.f('notificationlog_user_id'), table_name='notificationlog')
    op.drop_constraint(None, 'notificationlog', type_='foreignkey')
    op.create_foreign_key(None, 'notificationlog', 'BettingOpportunity', ['opportunity_id'], ['id'])
    op.alter_column('team', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('team_league_id'), table_name='team')
    op.drop_index(op.f('team_name_league_id'), table_name='team')
    op.alter_column('telegramuser', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('telegramuser_telegram_id'), table_name='telegramuser')
    # ### end Alembic commands ###
